openapi: 3.0.1
info:
  title: Swagger Petstore
  version: 1.0.0
tags:
  - name: pet
servers:
  - url: /api/
paths:
  /pet/{petId}:
    get:
      tags:
        - pet
      summary: Find pet by ID
      operationId: getPetById
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Pet not found
          content: {}
components:
  schemas:
    Pet:
      required:
        - pet_id
        - name
      type: object
      properties:
        pet_id:
          type: integer
          format: int64
        name:
          type: string
          example: doggie
